git clone git@github.com:FooSoft/vim-argwrap              bundle/vim-argwrap
git clone git@github.com:airblade/vim-gitgutter           bundle/vim-gitgutter
git clone git@github.com:ajh17/vimcompletesme             bundle/vimcompletesme
git clone git@github.com:altercation/vim-colors-solarized bundle/vim-colors-solarized
git clone git@github.com:bling/vim-airline                bundle/vim-airline
git clone git@github.com:bling/vim-bufferline             bundle/vim-bufferline
git clone git@github.com:godlygeek/tabular                bundle/tabular
git clone git@github.com:iamcco/markdown-preview.nvim     bundle/markdown-preview.nvim
git clone git@github.com:junegunn/fzf.vim                 bundle/fzf.vim
git clone git@github.com:mileszs/ack.vim                  bundle/ack.vim
git clone git@github.com:nathanaelkane/vim-indent-guides  bundle/vim-indent-guides
git clone git@github.com:scrooloose/nerdcommenter         bundle/nerdcommenter
git clone git@github.com:scrooloose/nerdtree              bundle/nerdtree
git clone git@github.com:sheerun/vim-polyglot             bundle/vim-polyglot
git clone git@github.com:slashmili/alchemist.vim          bundle/alchemist
git clone git@github.com:tpope/vim-endwise                bundle/vim-endwise
git clone git@github.com:tpope/vim-fugitive               bundle/vim-fugitive
git clone git@github.com:tpope/vim-rhubarb                bundle/vim-rhubarb
git clone git@github.com:vim-airline/vim-airline-themes   bundle/vim-airline-themes
git clone git@github.com:w0rp/ale                         bundle/ale
